# Generated by Django 6.0.5 on 2026-06-07 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0004_alter_contact_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='user',
            new_name='assigned_to',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='user',
            new_name='assigned_to',
        ),
    ]
