# Generated by Django 6.0.5 on 2026-06-07 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0006_stage_product_pipeline_deal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stage',
        ),
    ]
