# Generated by Django 6.0.5 on 2026-06-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0007_delete_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='deals', to='crm_app.contact'),
        ),
    ]
