# Generated by Django 6.0.5 on 2026-06-07 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0008_alter_deal_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='crm_app.pipeline'),
        ),
    ]
