# Generated by Django 6.0.5 on 2026-06-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_team_alter_user_role_user_team'),
        ('crm_app', '0009_alter_deal_pipeline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='team',
        ),
        migrations.AddField(
            model_name='product',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='products', to='auth_app.team'),
        ),
    ]
