# Generated by Django 6.0.5 on 2026-06-07 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0011_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipeline',
            name='team',
        ),
    ]
