# Generated by Django 6.0.5 on 2026-06-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0013_dealstagehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealstagehistory',
            name='old_stage',
            field=models.CharField(choices=[('new_lead', 'New Lead'), ('qualification', 'Qualification'), ('proposal_sent', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost')], max_length=20),
        ),
    ]
