# Generated by Django 6.0.5 on 2026-06-11 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0014_alter_dealstagehistory_old_stage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DealStageHistory',
        ),
    ]
