# Generated by Django 6.0.5 on 2026-06-15 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0016_dealstagehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='product',
            field=models.ForeignKey(default='40ec2b0d-b11a-48e1-9940-88d49c45e1b5', on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='crm_app.product'),
            preserve_default=False,
        ),
    ]
