# Generated by Django 6.0.5 on 2026-06-19 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0019_activity_activitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='activity',
            field=models.ForeignKey(default='e77ba342-f0db-49a7-8683-e7f9f0f8f9c8', on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='crm_app.activity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('task', 'Task'), ('proposal', 'Send a proposal'), ('contract', 'Signing the contract'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='activity',
            name='assigned_to',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='contact',
            field=models.ForeignKey(default='fbe99eed-9202-4f08-9284-338f9b29a305', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm_app.contact'),
            preserve_default=False,
        ),
    ]
