# Generated by Django 6.0.5 on 2026-06-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0020_activitylog_activity_alter_activity_activity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='new_data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='old_data',
            field=models.JSONField(null=True),
        ),
    ]
