# Generated by Django 6.0.5 on 2026-06-20 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0022_notification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notification_read_notify_idx',
            old_name='crm_app_not_read_at_045edf_idx',
        ),
    ]
