# Generated by Django 6.0.5 on 2026-06-20 21:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0023_rename_crm_app_not_read_at_045edf_idx_notification_read_notify_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notification_read_notify_idx',
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['sent_at', 'notify_at'], name='notification_read_notify_idx'),
        ),
    ]
