# Generated by Django 6.0.5 on 2026-06-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0025_activityscript'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='is_final',
        ),
        migrations.AddField(
            model_name='deal',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
