# Generated by Django 6.0.5 on 2026-06-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0026_remove_deal_is_final_deal_closed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('closed', 'Closed')], default='new', max_length=20),
        ),
    ]
