# Generated by Django 6.0.5 on 2026-07-12 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0027_alter_deal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='crm_app.activityscript'),
        ),
    ]
