# Generated by Django 6.0.5 on 2026-07-12 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0028_activity_script'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='contacts',
        ),
        migrations.AddField(
            model_name='deal',
            name='contact',
            field=models.ForeignKey(default='fbe99eed-9202-4f08-9284-338f9b29a305', on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='crm_app.contact'),
            preserve_default=False,
        ),
    ]
