# Generated by Django 6.0.5 on 2026-07-13 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0029_remove_deal_contacts_deal_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='assigned_to',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='assigned_to',
            new_name='created_by',
        ),
        migrations.AlterField(
            model_name='activity',
            name='contact',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm_app.contact'),
        ),
    ]
