# Generated by Django 6.0.5 on 2026-07-31 10:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0030_rename_assigned_to_company_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityscript',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='crm_app.product'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm_app.product'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipelines', to='crm_app.product'),
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('manual', 'Manual'), ('periodic', 'Periodic'), ('team_deleted', 'Team Deleted'), ('user_removed_from_team', 'User removed from team'), ('product_removed_from_team', 'Product removed from team'), ('user_deleted', 'User deleted'), ('product_deleted', 'Product deleted')], default='manual', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('archived_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='archived',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='crm_app.archive'),
        ),
        migrations.AddField(
            model_name='deal',
            name='archived',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm_app.archive'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='archived',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipelines', to='crm_app.archive'),
        ),
    ]
