# Generated by Django 6.0.5 on 2026-07-31 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0031_alter_activityscript_product_alter_deal_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archive',
            old_name='status',
            new_name='archiving_type',
        ),
    ]
